import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="bg-slate-600">
      <body>
        <div className="w-full py-4 text-slate-50 bg-slate-900"> rave </div>
        {children}
      </body>
    </html>
  );
}
